version: "3.9"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Overwrites the run command 'CMD ["npm", "run", "dev"]' in the
    # Dockerfile.
    command: npm run dev
