version: "3.9"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - .:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
